version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Adjust host:container port mapping as needed
    environment:
      POSTGRES_USER: newusername  # Replace with your desired username
      POSTGRES_PASSWORD: newpassword  # Replace with your desired password
      POSTGRES_DB: postgres
